// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtvahszowxfxxjtglyub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dmFoc3pvd3hmeHhqdGdseXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDkzMzksImV4cCI6MjA2ODU4NTMzOX0.ohmGVhHsKJdkZi-jZ6wLqDxjmL8JO0ciiud9HxQVOKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});